### ISSUE TITLE
I need you to delete information.

### ISSUE THREAD

**Issue by ServicioAntifraude** [Melacon/WirelessTransportEmulator-MEC-extensions#1]
To the attention of Melacon,

We are from Telefonica Spain and we are managing every scam related with Telefonica.

We need you to delete the information of the email account with the domain @telefonica.com, it's in the line 23. This is sensitive information and its important that you delete it, please.

Thanks for your time,

Best Regards

**Comment by alexandrustancu** [comment]
Please be more specific in your request.

I don't understand what is the issue. Line 23 from where ? What email account are you referring to ?

Kind Regards

**Comment by ServicioAntifraude** [comment]
Hello again,

I mean this repository https://github.com/Melacon/WirelessTransportEmulator-MEC-extensions/blob/master/yang/microwave-model.yang, line 23 the email account mailto:thorsten.heinze@telefonica.com, if you need more information let us know.

Kind regards.

**Comment by alexandrustancu** [comment]
Hi,

I understand. That YANG file is a public document released by the ONF, it is not something belonging to this repository. You can find it here: https://github.com/OpenNetworkingFoundation/CENTENNIAL/blob/60f62df091e7205b58f70d31e3e198f97d3e53c4/models/yang/microwave-model.yang

Since it is public and not managed by this repository, I am not able to delete that information.

Kind Regards.

**Comment by ServicioAntifraude** [comment]
Thanks for the information, we are going to check this.

Kind regards.
